// ---------------------------------------------------
// version.hpp  Ver 17.08.11k  x86_64-apple-darwin10.0
// Serial No. 2017-0501-654321                        
// Copyright(c)2017 Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Fri Aug 11 10:43:16 PDT 2017

#define RMJ 17
#define RMN 8
#define RUP 11
#define RTP 10
